### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by eltonec** [RaphaelJenni/FirebaseUI-Angular#79] opened 2018-09-10 15:54 UTC
'ng serve' is ok, but 'ng build --prod' error occurred : can not resolve 'firebase/index' in 'src/app/app.module.ngfactory.js, and can not resolve 'firebaseui/dist/index' in ....

**Comment by RaphaelJenni** [comment] 2018-09-10 18:10
Duplicate of #76

**Closed by RaphaelJenni** 2018-09-10 18:10 UTC
