### ISSUE TITLE
Recaptach iframe not removed when FirebaseUI is removed

### ISSUE THREAD

**Issue by oobayly** [RaphaelJenni/FirebaseUI-Angular#154] opened 2021-05-07 08:37 UTC
When debugging an unrelated CSS issue I noticed a number of hidden divs had been added the body of the page.

Granted, this is somewhat contrived, but if the user were to flick between the home page and a sign-in page containing FirebaseUI multiple times we end up with something like this:
![image](https://user-images.githubusercontent.com/3430117/117421777-c0940700-af16-11eb-966b-8437bc47e167.png)

This is probably because the designers of FirebaseUI expected the page be reloaded afterwards so the iframes don't need to be removed, but as we're dealing with an SPA they remain in the page

For the time being, I've added the following in order to tidy up the remnants, but it would be advantageous for `FirebaseuiAngularLibraryComponent` to do this out of the box.

```typescript
  ngOnDestroy(): void {
    // HACK: Recaptcha adds some elements to to the body element. FirebaseUi doesn't tidy them up 
    // probably because it's been designed for multi-page sites.
    const challenges = document.querySelectorAll("body div div iframe[title='recaptcha challenge']");

    challenges.forEach((x) => {
      // Based on the selector, we know the iframe has two parents so we know they cannot be undefined
      document.body.removeChild(x.parentNode!.parentNode!);
    });
  }
```

**Comment by oobayly** [comment] 2021-05-07 08:37
Typo

**Comment by RaphaelJenni** [comment] 2021-05-08 12:32
@oobayly Thanks for reporting this. I checked it out and was able to reproduce it.

This div not only gets added when switching between pages, but it also gets added when selecting phone authentication, then cancel it, and then selecting phone authentication again.
Therefore this is not only an issue of SPAs and should be fixed by the firebaseui library in general.

Please open the issue there. If they won't fix it for some reason for the whole library, I can do it here with something like you suggested.

**Comment by oobayly** [comment] 2021-05-14 07:24
> This div not only gets added when switching between pages, but it also gets added when selecting phone authentication, then cancel it, and then selecting phone authentication again.

I hadn't considered that. I'll do as you suggest and create an issue upstream.

**Comment by RaphaelJenni** [comment] 2022-06-19 21:21
Closing due to inactivity.

**Closed by RaphaelJenni** 2022-06-19 21:21 UTC
Labels: bug, on hold
