### ISSUE TITLE
(signInSuccessWithAuthResult)="successCallback($event)" being called only with Google Authentication

### ISSUE THREAD

**Issue by sizilkrishna** [RaphaelJenni/FirebaseUI-Angular#108] opened 2019-11-06 15:06 UTC
Hello, 

I tried setting up a callback on successful login but strangely  the callback `(signInSuccessWithAuthResult)="successCallback($event)"`  is only being called when i login with google account, whenever i am trying to login with Email or Anonymous, this is not getting called.

Details: 

In my `app.module.ts`

```
const firebaseUiAuthConfig: firebaseui.auth.Config = {
  callbacks: {
    signInSuccessWithAuthResult: function(authResult, redirectUrl) {
      console.log('Father Callback!');
      return true;
    }
  },
  signInSuccessUrl: '/',
  signInFlow: 'redirect',
  signInOptions: [
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
    {
      scopes: [
        'public_profile',
        'email',
        'user_likes',
        'user_friends'
      ],
      customParameters: {
        'auth_type': 'reauthenticate'
      },
      provider: firebase.auth.FacebookAuthProvider.PROVIDER_ID
    },
    firebase.auth.TwitterAuthProvider.PROVIDER_ID,
    firebase.auth.GithubAuthProvider.PROVIDER_ID,
    {
      requireDisplayName: false,
      provider: firebase.auth.EmailAuthProvider.PROVIDER_ID
    },
    firebase.auth.PhoneAuthProvider.PROVIDER_ID,
    firebaseui.auth.AnonymousAuthProvider.PROVIDER_ID
  ],
  tosUrl: '<your-tos-link>',
  privacyPolicyUrl: '<your-privacyPolicyUrl-link>',
  credentialHelper: firebaseui.auth.CredentialHelper.NONE
};
```

signInSuccessWithAuthResult and signInSuccessUrl are working fine but when i try to custom redirect using router snapshot in component as,

```
    <firebase-ui 
    (signInSuccessWithAuthResult)="successCallback($event)" 
    (signInFailure)="errorCallback($event)">
    </firebase-ui>
```

then, `signInSuccessWithAuthResult` is only being called upon login from google, and is not being called when logging in through email or anonymous.

**`EDIT`**

I just noticed this, still problem is persistant.

https://github.com/RaphaelJenni/FirebaseUI-Angular/issues/81

**Comment by sizilkrishna** [comment] 2019-11-07 13:59
A working StackBlitz can be found here,

https://stackoverflow.com/questions/58748913/success-callback-of-firebase-login-not-invoking

**Comment by RaphaelJenni** [comment] 2019-11-07 15:02
Hi @sizilkrishna 
I just tested it out with my project keys and have found no issues. Make sure that you have email/password etc. enabled in the firebase console.

If it still doesn't work. Try the demo app provided in this project, maybe you find something there.
It that doesn't work as well, I have to check again.

**Comment by sizilkrishna** [comment] 2019-11-07 16:24
Hey @RaphaelJenni 

I'm sorry but i double checked that i have enabled anon, email, phone and google login. 

However i hope you understand logging in isn't the problem, everything is working smoothly, but its that after logging `(signInSuccessWithAuthResult)="successCallback($event)" ` is not being invoked in anon or email or phone login.

Here's the [StackBlitz](https://stackblitz.com/github/sizilkrishna/app-angular-onlinetools)

Case 1: Logging in with **Google**

![image](https://user-images.githubusercontent.com/56112138/68406053-23cc9e00-01a7-11ea-8bfc-0c7fd9be8ec7.png)

```
  successCallback(signInSuccessData) {
    console.log("Child Callback, Logged in! Redirecting to " + this.returnUrl);
    this.router.navigateByUrl(this.returnUrl);
  }
```
Is being called, as displayed in log file.

Case 2: Logging Anon

![image](https://user-images.githubusercontent.com/56112138/68406214-6c845700-01a7-11ea-9405-dc3e7694c888.png)

As you can see, i'm logged in still no callback of `successCallback()`.

**Comment by Konstantinos-Val** [comment] 2019-11-11 15:03
The issue is your angular code not the firebaseui-angular npm package. If you remove the `*ngIf="!afAuth.auth.currentUser"` from the div in your login.component.html then you will see that the callback "successCallback(signInSuccessData)" gets called after successfull login with email .

**Comment by Konstantinos-Val** [comment] 2019-11-28 11:43
@RaphaelJenni I think we are ok  and we can close this issue. I answered it at https://stackoverflow.com/questions/58748913/success-callback-of-firebase-login-not-invoking .

**Closed** 2019-11-29 10:26 UTC
